---
title: "susie_ann_opt_method_comparison"
author: "Udai"
date: "01/13/2021"
output: html_document
---


```{r}
#Comparing ELBO over course of optimization for the 3 optimization methods
G <- 6
alt_opt_itr <- 5
all_susie_ann_alpha <- list()
all_susie_ann_pi <- list()
all_susie_ann_w <- list()
all_susie_pi <- list()
all_susie_alpha <- list()
synth_data<-contrived_example(10, G)
print("Synthetic data A_Lst:")
print(synth_data$A_lst)
for (optim_method in c("SGD", "L-BFGS-B", "Adam")){
  print("Now using optimization method:")
  print(optim_method)
  res <- susie_ann(synth_data$susie_ann_X,synth_data$susie_ann_Y, synth_data$A_lst, G, FALSE, G,
                  L = 1, scaled_prior_variance=1.0, susie_ann_opt_itr=alt_opt_itr, elbo_optim_method=optim_method)
  all_susie_ann_pi[[itr]] <- res$final_pi
  all_susie_ann_w[[itr]] <- res$w
  all_susie_results <- res$raw_susie_results
  locus_susie_pi <- list()
  locus_susie_alpha <- list()
  locus_susie_ann_alpha <- list()
  for (g in 1:G){
    locus_susie_pi[[g]] <- all_susie_results[[g]]$pi
    locus_susie_alpha[[g]] <- all_susie_results[[g]]$alpha
    locus_susie_ann_alpha[[g]] <- res$susie_models[[g]]$alpha
  }
  all_susie_pi[[itr]] <- locus_susie_pi
  all_susie_alpha[[itr]] <- locus_susie_alpha
  all_susie_ann_alpha[[itr]] <- locus_susie_ann_alpha
}

```


```{r}
#Comparing opt. model from first and fifth iterations: what's changing?
#First doing 1 alt opt iteration
num_itr <- 20
all_synth_data <- list()
for (itr in 1:num_itr){
  all_synth_data[[itr]] <- contrived_example(10, G)
}
print("Data A_lst")
print(all_synth_data[[1]]$A_lst)
G <- 6
all_susie_ann_alpha <- list()
all_susie_ann_pi <- list()
all_susie_ann_w <- list()
all_susie_pi <- list()
all_susie_alpha <- list()
for (itr in 1:num_itr){
  synth_data<-all_synth_data[[itr]]
  res <- susie_ann(synth_data$susie_ann_X,synth_data$susie_ann_Y, synth_data$A_lst, G, FALSE, G,
                  L = 1, scaled_prior_variance=1.0, susie_ann_opt_itr=1, elbo_optim_method="L-BFGS-B")
  all_susie_ann_pi[[itr]] <- res$final_pi
  all_susie_ann_w[[itr]] <- res$w
  all_susie_results <- res$raw_susie_results
  locus_susie_pi <- list()
  locus_susie_alpha <- list()
  locus_susie_ann_alpha <- list()
  for (g in 1:G){
    locus_susie_pi[[g]] <- all_susie_results[[g]]$pi
    locus_susie_alpha[[g]] <- all_susie_results[[g]]$alpha
    locus_susie_ann_alpha[[g]] <- res$susie_models[[g]]$alpha
  }
  all_susie_pi[[itr]] <- locus_susie_pi
  all_susie_alpha[[itr]] <- locus_susie_alpha
  all_susie_ann_alpha[[itr]] <- locus_susie_ann_alpha
}

average_susie_ann_pi <- all_susie_ann_pi[[1]]
average_susie_ann_w <- all_susie_ann_w[[1]]
average_susie_ann_alpha <- all_susie_ann_alpha[[1]]
average_susie_pi <- all_susie_pi[[1]]
average_susie_alpha <- all_susie_alpha[[1]]


for (itr in 2:num_itr){
  average_susie_ann_w = all_susie_ann_w[[itr]] + average_susie_ann_w
  for (g in 1:G){
    average_susie_ann_pi[[g]] = all_susie_ann_pi[[itr]][[g]] + average_susie_ann_pi[[g]]
    average_susie_ann_alpha[[g]] = all_susie_ann_alpha[[itr]][[g]] + average_susie_ann_alpha[[g]]
    average_susie_pi[[g]] = all_susie_pi[[itr]][[g]] + average_susie_pi[[g]]
    average_susie_alpha[[g]] = all_susie_alpha[[itr]][[g]] + average_susie_alpha[[g]]
  }
}
average_susie_ann_w = average_susie_ann_w/num_itr
for (g in 1:G){
  average_susie_ann_pi[[g]] = average_susie_ann_pi[[g]]/num_itr
  average_susie_ann_alpha[[g]] = average_susie_ann_alpha[[g]]/num_itr
  average_susie_pi[[g]] = average_susie_pi[[g]]/num_itr
  average_susie_alpha[[g]] = average_susie_alpha[[g]]/num_itr
}

print("Average SuSiE Ann Pi:")
print(average_susie_ann_pi)
print("Average SuSiE Ann w:")
print(average_susie_ann_w)
print("Average SuSiE Ann Alpha:")
print(average_susie_ann_alpha)
print("Average SuSIE Pi:")
print(average_susie_pi)
print("Average SuSiE Alpha:")
print(average_susie_alpha)
```


```{r}
#Comparing opt. model from first and fifth iterations: what's changing?
#First doing 10 alt opt iteration
num_itr <- 20
all_synth_data <- list()
for (itr in 1:num_itr){
  all_synth_data[[itr]] <- contrived_example(10, G)
}
print("Data A_lst")
print(all_synth_data[[1]]$A_lst)
G <- 6
all_susie_ann_alpha <- list()
all_susie_ann_pi <- list()
all_susie_ann_w <- list()
all_susie_pi <- list()
all_susie_alpha <- list()
for (itr in 1:num_itr){
  synth_data<-all_synth_data[[itr]]
  res <- susie_ann(synth_data$susie_ann_X,synth_data$susie_ann_Y, synth_data$A_lst, G, FALSE, G,
                  L = 1, scaled_prior_variance=1.0, susie_ann_opt_itr=1, elbo_optim_method="L-BFGS-B")
  all_susie_ann_pi[[itr]] <- res$final_pi
  all_susie_ann_w[[itr]] <- res$w
  all_susie_results <- res$raw_susie_results
  locus_susie_pi <- list()
  locus_susie_alpha <- list()
  locus_susie_ann_alpha <- list()
  for (g in 1:G){
    locus_susie_pi[[g]] <- all_susie_results[[g]]$pi
    locus_susie_alpha[[g]] <- all_susie_results[[g]]$alpha
    locus_susie_ann_alpha[[g]] <- res$susie_models[[g]]$alpha
  }
  all_susie_pi[[itr]] <- locus_susie_pi
  all_susie_alpha[[itr]] <- locus_susie_alpha
  all_susie_ann_alpha[[itr]] <- locus_susie_ann_alpha
}

average_susie_ann_pi <- all_susie_ann_pi[[1]]
average_susie_ann_w <- all_susie_ann_w[[1]]
average_susie_ann_alpha <- all_susie_ann_alpha[[1]]
average_susie_pi <- all_susie_pi[[1]]
average_susie_alpha <- all_susie_alpha[[1]]


for (itr in 2:num_itr){
  average_susie_ann_w = all_susie_ann_w[[itr]] + average_susie_ann_w
  for (g in 1:G){
    average_susie_ann_pi[[g]] = all_susie_ann_pi[[itr]][[g]] + average_susie_ann_pi[[g]]
    average_susie_ann_alpha[[g]] = all_susie_ann_alpha[[itr]][[g]] + average_susie_ann_alpha[[g]]
    average_susie_pi[[g]] = all_susie_pi[[itr]][[g]] + average_susie_pi[[g]]
    average_susie_alpha[[g]] = all_susie_alpha[[itr]][[g]] + average_susie_alpha[[g]]
  }
}
average_susie_ann_w = average_susie_ann_w/num_itr
for (g in 1:G){
  average_susie_ann_pi[[g]] = average_susie_ann_pi[[g]]/num_itr
  average_susie_ann_alpha[[g]] = average_susie_ann_alpha[[g]]/num_itr
  average_susie_pi[[g]] = average_susie_pi[[g]]/num_itr
  average_susie_alpha[[g]] = average_susie_alpha[[g]]/num_itr
}

print("Average SuSiE Ann Pi:")
print(average_susie_ann_pi)
print("Average SuSiE Ann w:")
print(average_susie_ann_w)
print("Average SuSiE Ann Alpha:")
print(average_susie_ann_alpha)
print("Average SuSIE Pi:")
print(average_susie_pi)
print("Average SuSiE Alpha:")
print(average_susie_alpha)
```





